/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConsistencySvg: typeof import('./.vitepress/vitepress/components/globals/design/consistency-svg.vue')['default']
    ControllabilitySvg: typeof import('./.vitepress/vitepress/components/globals/design/controllability-svg.vue')['default']
    Dark: typeof import('./.vitepress/vitepress/components/icons/dark.vue')['default']
    DesignGuide: typeof import('./.vitepress/vitepress/components/globals/design-guide.vue')['default']
    EfficiencySvg: typeof import('./.vitepress/vitepress/components/globals/design/efficiency-svg.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FeedbackSvg: typeof import('./.vitepress/vitepress/components/globals/design/feedback-svg.vue')['default']
    IRiCodeLine: typeof import('~icons/ri/code-line')['default']
    IRiExternalLinkLine: typeof import('~icons/ri/external-link-line')['default']
    IRiFileCopyLine: typeof import('~icons/ri/file-copy-line')['default']
    IRiFlaskLine: typeof import('~icons/ri/flask-line')['default']
    IRiGithubLine: typeof import('~icons/ri/github-line')['default']
    IRiTranslate2: typeof import('~icons/ri/translate2')['default']
    Light: typeof import('./.vitepress/vitepress/components/icons/light.vue')['default']
    ToggleSidebarBtn: typeof import('./.vitepress/vitepress/components/subnav/toggle-sidebar-btn.vue')['default']
    VpApp: typeof import('./.vitepress/vitepress/components/vp-app.vue')['default']
    VpContent: typeof import('./.vitepress/vitepress/components/vp-content.vue')['default']
    VpDemo: typeof import('./.vitepress/vitepress/components/vp-demo.vue')['default']
    VpDocContent: typeof import('./.vitepress/vitepress/components/vp-doc-content.vue')['default']
    VpExample: typeof import('./.vitepress/vitepress/components/demo/vp-example.vue')['default']
    VpHamburger: typeof import('./.vitepress/vitepress/components/navbar/vp-hamburger.vue')['default']
    VpLink: typeof import('./.vitepress/vitepress/components/common/vp-link.vue')['default']
    VpMenu: typeof import('./.vitepress/vitepress/components/navbar/vp-menu.vue')['default']
    VpMenuLink: typeof import('./.vitepress/vitepress/components/navbar/vp-menu-link.vue')['default']
    VpNav: typeof import('./.vitepress/vitepress/components/vp-nav.vue')['default']
    VpNavbar: typeof import('./.vitepress/vitepress/components/vp-navbar.vue')['default']
    VpPageNav: typeof import('./.vitepress/vitepress/components/doc-content/vp-page-nav.vue')['default']
    VpSearch: typeof import('./.vitepress/vitepress/components/navbar/vp-search.vue')['default']
    VpSidebar: typeof import('./.vitepress/vitepress/components/vp-sidebar.vue')['default']
    VpSidebarLink: typeof import('./.vitepress/vitepress/components/sidebar/vp-sidebar-link.vue')['default']
    VpSocialLink: typeof import('./.vitepress/vitepress/components/navbar/vp-social-link.vue')['default']
    VpSocialLinks: typeof import('./.vitepress/vitepress/components/navbar/vp-social-links.vue')['default']
    VpSourceCode: typeof import('./.vitepress/vitepress/components/demo/vp-source-code.vue')['default']
    VpSubnav: typeof import('./.vitepress/vitepress/components/vp-subnav.vue')['default']
    VpSwitch: typeof import('./.vitepress/vitepress/components/common/vp-switch.vue')['default']
    VpThemeToggler: typeof import('./.vitepress/vitepress/components/navbar/vp-theme-toggler.vue')['default']
    VpTranslation: typeof import('./.vitepress/vitepress/components/navbar/vp-translation.vue')['default']
  }
}
